# Setup
title:               Biased
tagline:             'Um Blog Sem Tema Unificador'
description:         'Um blog opinativo completamente enviesado'
url:                 https://ferreirapedroh.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pedro Ferreira
  url:               https://twitter.com/phgferreira
  email:             pedroferreira@ieee.org

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
